### PR TITLE
Fix/proper cli args handling

### PR DESCRIPTION
**Pull request by mbenapari**
1. **Unified Prompt Handling for Ollama and GPT**: Updated the commit message prompt for Ollama to align with the GPT model, ensuring consistency across both platforms.
2. **Enhanced CLI Flag Handling**: Improved how CLI flags are processed to provide a smoother user experience.
3. **Provider Specification for OpenAI**: Users can now specify the OpenAI provider by passing the --PROVIDER=openai flag.
4. **Flexible Model Selection for Ollama**: When using Ollama, users should specify the model by passing --PROVIDER=ollama --MODEL=llama3.1 (or another desired model).

### CODE REVIEW

**Comment by insulineru** [comment]
@HamduSalih is it ready for review?

**Comment by mbenapari** [comment]
@insulineru yes please

**Comment by silasvasconcelos** [comment]
@mbenapari your PR has conflicts, can you check, thanks.

I need this fix too =)

**Comment by mbenapari** [comment]
> @mbenapari your PR has conflicts, can you check, thanks.
> 
> I need this fix too =)

@insulineru please check it out

**Review by insulineru — APPROVED** [review]

**Pull request merged**
